name: Deploy to SFTP

on:
  push:
    branches:
      - master  # Trigger deployment on changes pushed to the master branch

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Backend via SFTP
        if: github.ref == 'refs/heads/master'  # Ensure deployment only happens for the master branch
        run: |
          lftp -e "set ssl:verify-certificate no; open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} 287586.w86.wedos.net && mirror -R Fitmo_backend /www/subdom/beTest"

  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust to your required Node.js version

      - name: Install Frontend dependencies
        run: |
          cd Fitmo_frontend
          npm install

      - name: Build Frontend project
        run: |
          cd Fitmo_frontend
          npm run build  # Replace with your actual build command for the frontend (e.g., npm run build)

      - name: Deploy Frontend via SFTP
        if: github.ref == 'refs/heads/master'  # Ensure deployment only happens for the master branch
        run: |
          lftp -e "set ssl:verify-certificate no; open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} 287586.w86.wedos.net && mirror -R Fitmo_frontend/dist /www/subdom/devTest"
