name: Deploy to SFTP

on:
  push:
    branches:
      - master  # Change this to your target branch

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Backend to SFTP server
        uses: depsypher/sftp-deploy@v3
        with:
          server: 287586.w86.wedos.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localPath: Fitmo_backend  # Directory containing backend files
          remotePath: /www/subdom/beTest  # Target directory on the server for backend

  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Frontend to SFTP server
        uses: depsypher/sftp-deploy@v3
        with:
          server: 287586.w86.wedos.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localPath: Fitmo_frontend  # Directory containing frontend files
          remotePath: /www/subdom/devTest  # Target directory on the server for frontend
