name: Deploy to SFTP

on:
  push:
    branches:
      - master  # Change this to your target branch

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Backend via SFTP
        run: |
          apt-get update && apt-get install -y lftp
          lftp -c "open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} sftp://287586.w86.wedos.net && mirror -R Fitmo_backend /www/subdom/beTest"

  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Frontend via SFTP
        run: |
          apt-get update && apt-get install -y lftp
          lftp -c "open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} sftp://287586.w86.wedos.net && mirror -R Fitmo_frontend /www/subdom/devTest"
